version: '1'
services:
  express-app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306"
    volumes:
      - ./db-scripts:/docker-entrypoint-initdb.d